### ISSUE TITLE
xpath.parse output

### ISSUE THREAD

**Issue by bcail** [emory-libraries/eulxml#32]
I'm working with the following xpath:
hydra:access[@type='read']/hydra:machine/hydra:group

When I put that into xpath.parse, I get a Binary Expression as the type of the result.

Is that correct, or is there an issue with the parsing?

**Comment by rlskoeser** [comment]
@bcail I think that's right for how eulxml.xpath works and thinks about xpaths.

I played around with it a little in the python console, and the binary expression has a `left`, `right`, and `op` - in this case, the operator is the `/` connector.    Here's the console output if that gives you any more information.

```
>>> path = parse("hydra:access[@type='read']/hydra:machine/hydra:group")
>>> path
<BinaryExpression hydra:access[@type='read']/hydra:machine / hydra:group>
>>> path.left
<BinaryExpression hydra:access[@type='read'] / hydra:machine>
>>> path.right
<Step hydra:group>
>>> path.op
'/'
>>> path.left.left
<Step hydra:access[@type='read']>
>>> path.left.op
'/'
>>> path.left.right
<Step hydra:machine>
>>>
```

Does that help at all?  What is it you're trying to do?

**Comment by bcail** [comment]
Thanks - helps to rule out one possibility. :)

I'm trying to port [bdrxml](https://github.com/Brown-University-Library/bdrxml) to python 2 & 3 compatible code (bdrxml is what we've built on top of eulxml; currently it's just python2).

I'm getting the following traceback, but it only happens with python2 (in python3, the test passes fine).
`
Traceback (most recent call last):
  File "/bdrxml/test/rights_test.py", line 248, in test_add_users_and_build_hydra
    rights = self.builder.build_hydra()
  File "/bdrxml/bdrxml/rights.py", line 205, in build_hydra
    return HydraRightsBuilder(self).build()
  File "/bdrxml/bdrxml/rights.py", line 258, in build
    rights.read_access_group = groups
  File "/bdrxml/env/local/lib/python2.7/site-packages/eulxml/xmlmap/core.py", line 149, in __set__
    return self.field.set_for_node(obj.node, obj.context, value)
  File "/bdrxml/env/local/lib/python2.7/site-packages/eulxml/xmlmap/fields.py", line 81, in set_for_node
    return self.manager.set(self.xpath, self.parsed_xpath, node, context, self.mapper, value)
  File "/bdrxml/env/local/lib/python2.7/site-packages/eulxml/xmlmap/fields.py", line 847, in set 
    current_list[i] = value[i]
  File "/bdrxml/env/local/lib/python2.7/site-packages/eulxml/xmlmap/fields.py", line 758, in __setitem__
    match = _create_xml_node(self.xast, self.node, self.context, insert_index)
  File "/bdrxml/env/local/lib/python2.7/site-packages/eulxml/xmlmap/fields.py", line 312, in _create_xml_node
    left_node = _find_xml_node(left_xpath, node, context)
  File "/bdrxml/env/local/lib/python2.7/site-packages/eulxml/xmlmap/fields.py", line 274, in _find_xml_node
    matches = node.xpath(xpath, **context)
  File "src/lxml/lxml.etree.pyx", line 1587, in lxml.etree._Element.xpath (src/lxml/lxml.etree.c:57884)
  File "src/lxml/xpath.pxi", line 307, in lxml.etree.XPathElementEvaluator.__call__ (src/lxml/lxml.etree.c:166905)
  File "src/lxml/xpath.pxi", line 227, in lxml.etree._XPathEvaluatorBase._handle_result (src/lxml/lxml.etree.c:165864)

XPathEvalError: Invalid predicate
`

Have you run into that exception?

**Comment by rlskoeser** [comment]
I've seen that exception before, but I can't think of any case where I've seen it that would be helpful.   It does seem awfully suspicious that the test works fine under python 3, though.  Maybe there's a bug in the eulxml python2/3 compatibility that we haven't caught yet somehow.

**Comment by bcail** [comment]
Thanks. I'll close this and let you know if I find anything.

**Comment by bcail** [comment]
Turned out to just be an environment issue or something - the test passes now.

**Comment by rlskoeser** [comment]
Ok, glad to hear it's working.
